Major rewrite

diff --git a/bdbusy b/bdbusy
--- a/bdbusy
+++ b/bdbusy
@@ -1,63 +1,136 @@
 #!/bin/bash
 
-#----------------------------------------------------------------------------
-# BDBusy
-# Copyright (C) 2012 Nathan Shearer
-#
-# This program is free software; you can redistribute it and/or modify it
-# under the terms of the GNU General Public License version 2 as published by
-# the Free Software Foundation.
-#
-# This program is distributed in the hope that it will be useful, but WITHOUT
-# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
-# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
-# more details.
-#
-# You should have received a copy of the GNU General Public License along
-# with this program; if not, write to:
-#   The Free Software Foundation Inc.
-#   51 Franklin Street
-#   Fifth Floor
-#   Boston, MA
-#   02110-1301
-#   USA
-
+NAME="bdbusy"
+CODENAME="bdbusy"
 COPYRIGHT="Copyright (C) 2012 Nathan Shearer"
+LICENSE="GNU General Public License 2.0"
 VERSION="0.0.0.0"
 
 # \brief Ensures dependencies are present
 # \param $@ The dependencies to check for
-function shearer_check_dependencies
+function bdbusy_check_dependencies
 {
 	for TOOL in "$@"; do
 		if ! type "$TOOL" >/dev/null 2>/dev/null; then
-			echo "$0: \"$TOOL\" is required for this application to work correctly." >&2
+			echo "$CODENAME: \"$TOOL\" is required for this application to work correctly." >&2
 			exit
 		fi
 	done
 }
 
-shearer_check_dependencies blockdev dd sleep
+# \brief Displays the help and exits the program
+function bdbusy_help
+{
+	#     01234567890123456789012345678901234567890123456789012345678901234567890123456789
+	echo "Synopsis:"
+	echo "  Periodically reads data from a block device keeping it busy"
+	echo
+	echo "Usage:"
+	echo "  $CODENAME [options] BLOCK_DEVICE"
+	echo
+	echo "Options:"
+	echo "  -h, --help"
+	echo "    Display this help message and exit."
+	echo "  -v"
+	echo "    Show each disk read. The same as --verbose 1."
+	echo "  --verbose #"
+	echo "    Use more or less verbose output. Valid values are from 0 to 1 inclusive:"
+	echo "      0  Default. No output"
+	echo "      1  Show each disk read"
+	echo
+	echo "Examples:"
+	echo "  $CODENAME /dev/disk/by-id/ata-ST8000AS0002-1NA17Z_00000000"
+	echo "  $CODENAME -v /dev/disk/by-id/ata-ST8000AS0002-1NA17Z_00000000"
+	echo
+	echo "Version:"
+	echo "  $NAME $VERSION"
+	echo "  $COPYRIGHT"
+	echo "  Licensed under $LICENSE"
+	exit;
+}
 
-PERIOD="5s"
-BLOCKSIZE="4096"
+#------------------------------------------------------------------------------
+# default configuration
+#
 BLOCKS="256" #1MB
+BLOCKSIZE="4096"
+PERIOD="5s"
+VERBOSE=0
 
+#------------------------------------------------------------------------------
+# config files
+#
+if [ -r /etc/$CODENAME.conf ]; then
+	. /etc/$CODENAME.conf
+fi
+if [ -r ~/.$CODENAME.conf ]; then
+	. ~/.$CODENAME.conf
+fi
+
+#------------------------------------------------------------------------------
+# command line arguments
+#
+
+if [ $# -eq 0 ]; then
+	bdbusy_help
+	exit 1
+fi
+
+THIS="$0"
+while [ $# -ne 0 ]; do
+	case "$1" in
+		"-h"|"--help")
+			bdbusy_help
+			exit
+			;;
+		"-v")
+			VERBOSE=1
+			shift
+			;;
+		"--verbose")
+			VERBOSE="$2"
+			shift 2
+			;;
+		*)
+			break;;
+	esac
+done
+
+if [ $# -eq 0 ]; then
+	echo "error: Missing BLOCK_DEVICE argument."
+	exit 1
+fi
+if [ $# -gt 1 ]; then
+	bdbusy_help
+	exit 1
+fi
 DEVICE="$1"
 
-DEVICE_BYTES=`blockdev --getsize64 $DEVICE`
+#------------------------------------------------------------------------------
+# prepare environment
+
+bdbusy_check_dependencies blockdev dd sleep
+
+#------------------------------------------------------------------------------
+# begin execution
+
+DEVICE_BYTES=$(blockdev --getsize64 "$DEVICE")
 DEVICE_BLOCKS=$(( $DEVICE_BYTES / $BLOCKSIZE ))
 
 if [ $BLOCKS -gt $DEVICE_BLOCKS ]; then
-	echo "Error: You are attempting to read $BLOCKS blocks from a device which only contains $DEVICE_BLOCKS blocks."
+	echo "error: Attempting to read $BLOCKS blocks from a device which only contains $DEVICE_BLOCKS blocks."
 	exit 1
 fi
 
 while true; do
 	RANDOM64=$(( $RANDOM * $RANDOM * $RANDOM * $RANDOM ))
 	START=$(( $RANDOM64 % ( $DEVICE_BLOCKS - $BLOCKS ) ))
-	printf "Reading $BLOCKS blocks from '$DEVICE' starting at block $START... "
+	if [ "$VERBOSE" -ge 1 ]; then
+		echo -n "Reading $BLOCKS blocks from ‘$DEVICE’ at block $START..."
+	fi
 	dd if="$DEVICE" bs="$BLOCKSIZE" skip=$START count="$BLOCKS" of=/dev/null 2>/dev/null
-	echo "Done."
+	if [ "$VERBOSE" -ge 1 ]; then
+		echo " done."
+	fi
 	sleep $PERIOD
 done
